name: Nikkei notification
on:
  schedule:
    - cron: '25 5 * * *'
  workflow_dispatch:
    inputs:
      debug:
        description: "Debug flag. empty is meaning 'false'. else mean 'true'."
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    env:
      DEBUG: ${{ github.event.inputs.debug }}
      TARGET_STOCK_NAME: ${{ secrets.TARGET_STOCK_NAME }}
      LINEBOT_ACCESS_TOKEN: ${{ secrets.LINEBOT_ACCESS_TOKEN }}
      MY_LINE_ID: ${{ secrets.MY_LINE_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Cache
        uses: actions/cache@v2
        id: pipenv-cache
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.pipenv-cache.outputs.cache-hit != 'true'
        run: pipenv sync --dev
      - name: Exec🍏
        run: pipenv run exec
